AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SubnetID:
    Type: String
Resources:
  mydemoenv:
    Type: AWS::ElasticBeanstalk::Environment
    Properties: 
      ApplicationName: 
        Ref: sampleApplication
        Description: "AWS Elastic Beanstalk Environment running PHP Sample Application"
      EnvironmentName: SamplePHPEnvironment
      TemplateName: DefaultConfiguration
      VersionLabel: "Initial Version"
